name: Java Compilation

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'  # Change this to your desired Java version

    - name: Compile Java Source Files
      run: |
        javac -d ./build src/com/pacman/*.java
        javac -cp "./lib/*:./build" -d ./build src/com/pacman/*.java

