name: Java Compilation

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # You can use other distributions like 'adopt', 'adopt@1.11', 'openjdk', etc.
        java-version: '21' # Adjust the Java version as needed
        architecture: 'x64' # Change this if needed
        job-status: 'success'


    - name: Compile Java Source Files
      run: |
        javac -d ./build src/com/pacman/*.java
        javac -cp "./lib/*:./build" -d ./build src/com/pacman/*.java

